//! Runtime support library for binaries generated by `aot-llm`.
//!
//! Every file in this directory is copied verbatim into the generated
//! project as `src/rt/`, so it must only depend on `std`.
#![allow(dead_code, unused_imports, clippy::missing_safety_doc, clippy::needless_range_loop)]

pub mod app;
pub mod chat;
pub mod matvec;
pub mod ops;
pub mod pool;
pub mod quant;
pub mod quantize;
pub mod sampler;
pub mod state;
pub mod tokenizer;
pub mod weights;
